# Generated by Django 3.1 on 2021-01-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('DisplayName', models.CharField(max_length=100)),
                ('Query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('DisplayName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('DisplayName', models.CharField(max_length=100)),
                ('Query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EffectFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('DisplayName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('DisplayName', models.CharField(max_length=100)),
                ('Query', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('Order',), name='Part_unique'),
        ),
        migrations.AddConstraint(
            model_name='effectfilter',
            constraint=models.UniqueConstraint(fields=('Order',), name='EffectFilter_unique'),
        ),
        migrations.AddField(
            model_name='effect',
            name='FilterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchTraits.effectfilter'),
        ),
        migrations.AddConstraint(
            model_name='conditionfilter',
            constraint=models.UniqueConstraint(fields=('Order',), name='ConditionFilter_unique'),
        ),
        migrations.AddField(
            model_name='condition',
            name='FilterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchTraits.conditionfilter'),
        ),
        migrations.AddConstraint(
            model_name='effect',
            constraint=models.UniqueConstraint(fields=('Order', 'FilterID'), name='Effect_unique'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('Order', 'FilterID'), name='Condition_unique'),
        ),
    ]
