# Generated by Django 3.1.6 on 2021-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTraits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('Value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordtag',
            constraint=models.UniqueConstraint(fields=('Order',), name='WordTag_unique'),
        ),
    ]
