# Generated by Django 3.1.6 on 2021-06-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTraits', '0002_auto_20210604_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordtag',
            old_name='Value',
            new_name='DisplayName',
        ),
    ]
