from django.db import models

#models変更時は、forms/viewsでのtable参照箇所をすべてコメントアウト。(viewはreturn "aaa"　等に置き換え、formsは全削除可能。importも要削除。)

ALTER_CHOICES = (
    (0, ''),
    (1, '【改造】'),
    (2, '【改造BIG】'),
)

class Unit(models.Model):
    MSName = models.CharField(max_length=100)
    Attribute = models.CharField(max_length=10)
    MSNumber = models.CharField(max_length=50)
    WorkName = models.CharField(max_length=100)
    Rarity = models.IntegerField()
    ShowcaseTweet = models.CharField(max_length=1000, null=True)
    GundamwikiName = models.CharField(max_length=100, null=True)
    GundamwikiIntro = models.CharField(max_length=200, null=True)
    PrebanCode = models.CharField(max_length=20, null=True)
    PrebanName = models.CharField(max_length=1000, null=True)

class Status(models.Model):
    PartsName = models.CharField(max_length=100)
    Category = models.CharField(max_length=20)
    Unit = models.ForeignKey('Unit', null = True,on_delete = models.SET_NULL)
    Attribute = models.CharField(max_length=20)
    MaxRarity = models.IntegerField()
    CombinedCategory = models.CharField(max_length=20, null=True)
    AItype = models.CharField(max_length=20, null=True)
    Joblisence= models.CharField(max_length=20, null=True)
    Wordtag1 = models.CharField(max_length=10)
    Wordtag2 = models.CharField(max_length=10)
    Lv80Armor = models.IntegerField(default=0)
    Lv80MeleeATK = models.IntegerField(default=0)
    Lv80ShotATK = models.IntegerField(default=0)
    Lv80MeleeDEF = models.IntegerField(default=0)
    Lv80ShotDEF = models.IntegerField(default=0)
    Lv80BeamRES = models.IntegerField(default=0)
    Lv80PhysRES = models.IntegerField(default=0)
    Lv90Armor = models.IntegerField(default=0)
    Lv90MeleeATK = models.IntegerField(default=0)
    Lv90ShotATK = models.IntegerField(default=0)
    Lv90MeleeDEF = models.IntegerField(default=0)
    Lv90ShotDEF = models.IntegerField(default=0)
    Lv90BeamRES = models.IntegerField(default=0)
    Lv90PhysRES = models.IntegerField(default=0)
    Lv99Armor = models.IntegerField(default=0)
    Lv99MeleeATK = models.IntegerField(default=0)
    Lv99ShotATK = models.IntegerField(default=0)
    Lv99MeleeDEF = models.IntegerField(default=0)
    Lv99ShotDEF = models.IntegerField(default=0)
    Lv99BeamRES = models.IntegerField(default=0)
    Lv99PhysRES = models.IntegerField(default=0)   
    Traits1Name = models.CharField(max_length=100, null=True)
    T1Lv1Effect = models.CharField(max_length=10, null=True)
    T1Lv2Effect = models.CharField(max_length=10, null=True)
    T1Lv3Effect = models.CharField(max_length=10, null=True)
    T1Lv4Effect = models.CharField(max_length=10, null=True)
    T1Lv5Effect = models.CharField(max_length=10, null=True)
    T1Lv6Effect = models.CharField(max_length=10, null=True)
    T1Lv7Effect = models.CharField(max_length=10, null=True)
    T1Lv8Effect = models.CharField(max_length=10, null=True)
    T1Lv9Effect = models.CharField(max_length=10, null=True)
    T1Lv10Effect = models.CharField(max_length=10, null=True)
    Traits2Name = models.CharField(max_length=100, null=True)
    T2Lv1Effect = models.CharField(max_length=10, null=True)
    T2Lv2Effect = models.CharField(max_length=10, null=True)
    T2Lv3Effect = models.CharField(max_length=10, null=True)
    T2Lv4Effect = models.CharField(max_length=10, null=True)
    T2Lv5Effect = models.CharField(max_length=10, null=True)
    T2Lv6Effect = models.CharField(max_length=10, null=True)
    T2Lv7Effect = models.CharField(max_length=10, null=True)
    T2Lv8Effect = models.CharField(max_length=10, null=True)
    T2Lv9Effect = models.CharField(max_length=10, null=True)
    T2Lv10Effect = models.CharField(max_length=10, null=True)
    SkillName = models.CharField(max_length=50, null=True)
    SkillCategory = models.CharField(max_length=10, null=True)
    SkillText = models.CharField(max_length=200, null=True)
    SLv1Pierce = models.CharField(max_length=10, null=True)
    SLv1Power = models.CharField(max_length=10, null=True)
    SLv1Magazine = models.IntegerField(null=True)
    SLv1Effect = models.CharField(max_length=10, null=True)
    SLv1Effecttime = models.IntegerField(null=True)
    SLv1Cooldown = models.CharField(max_length=20, null=True)
    SLv2Pierce = models.CharField(max_length=10, null=True)
    SLv2Power = models.CharField(max_length=10, null=True)
    SLv2Magazine = models.IntegerField(null=True)
    SLv2Effect = models.CharField(max_length=10, null=True)
    SLv2Effecttime = models.IntegerField(null=True)
    SLv2Cooldown = models.CharField(max_length=20, null=True)
    SLv3Pierce = models.CharField(max_length=10, null=True)
    SLv3Power = models.CharField(max_length=10, null=True)
    SLv3Magazine = models.IntegerField(null=True)
    SLv3Effect = models.CharField(max_length=10, null=True)
    SLv3Effecttime = models.IntegerField(null=True)
    SLv3Cooldown = models.CharField(max_length=20, null=True)
    SLv4Pierce = models.CharField(max_length=10, null=True)
    SLv4Power = models.CharField(max_length=10, null=True)
    SLv4Magazine = models.IntegerField(null=True)
    SLv4Effect = models.CharField(max_length=10, null=True)
    SLv4Effecttime = models.IntegerField(null=True)
    SLv4Cooldown = models.CharField(max_length=20, null=True)
    SLv5Pierce = models.CharField(max_length=10, null=True)
    SLv5Power = models.CharField(max_length=10, null=True)
    SLv5Magazine = models.IntegerField(null=True)
    SLv5Effect = models.CharField(max_length=10, null=True)
    SLv5Effecttime = models.IntegerField(null=True)
    SLv5Cooldown = models.CharField(max_length=20, null=True)
    SLv6Pierce = models.CharField(max_length=10, null=True)
    SLv6Power = models.CharField(max_length=10, null=True)
    SLv6Magazine = models.IntegerField(null=True)
    SLv6Effect = models.CharField(max_length=10, null=True)
    SLv6Effecttime = models.IntegerField(null=True)
    SLv6Cooldown = models.CharField(max_length=20, null=True)
    SLv7Pierce = models.CharField(max_length=10, null=True)
    SLv7Power = models.CharField(max_length=10, null=True)
    SLv7Magazine = models.IntegerField(null=True)
    SLv7Effect = models.CharField(max_length=10, null=True)
    SLv7Effecttime = models.IntegerField(null=True)
    SLv7Cooldown = models.CharField(max_length=20, null=True)
    SLv8Pierce = models.CharField(max_length=10, null=True)
    SLv8Power = models.CharField(max_length=10, null=True)
    SLv8Magazine = models.IntegerField(null=True)
    SLv8Effect = models.CharField(max_length=10, null=True)
    SLv8Effecttime = models.IntegerField(null=True)
    SLv8Cooldown = models.CharField(max_length=20, null=True)
    SLv9Pierce = models.CharField(max_length=10, null=True)
    SLv9Power = models.CharField(max_length=10, null=True)
    SLv9Magazine = models.IntegerField(null=True)
    SLv9Effect = models.CharField(max_length=10, null=True)
    SLv9Effecttime = models.IntegerField(null=True)
    SLv9Cooldown = models.CharField(max_length=20, null=True)
    SLv10Pierce = models.CharField(max_length=10, null=True)
    SLv10Power = models.CharField(max_length=10, null=True)
    SLv10Magazine = models.IntegerField(null=True)
    SLv10Effect = models.CharField(max_length=10, null=True)
    SLv10Effecttime = models.IntegerField(null=True)
    SLv10Cooldown = models.CharField(max_length=20, null=True)

    def __str__(self):
        Attribute = self.Unit.Attribute if self.Unit else ''
        return f"{self.PartsName} {self.Category} {Attribute}"

# class Skill(models.Model):
#     Status = models.ForeignKey('Status', null = True,on_delete = models.SET_NULL)
#     SkillName = models.CharField(max_length=50)
#     SkillCategory = models.CharField(max_length=10)
#     SkillText = models.CharField(max_length=200)
#     SLv1Pierce = models.CharField(max_length=10, null=True)
#     SLv1Power = models.CharField(max_length=10, null=True)
#     SLv1Magazine = models.IntegerField(null=True)
#     SLv1Effect = models.CharField(max_length=10, null=True)
#     SLv1Effecttime = models.IntegerField(null=True)
#     SLv1Cooldown = models.CharField(max_length=20)
#     SLv2Pierce = models.CharField(max_length=10, null=True)
#     SLv2Power = models.CharField(max_length=10, null=True)
#     SLv2Magazine = models.IntegerField(null=True)
#     SLv2Effect = models.CharField(max_length=10, null=True)
#     SLv2Effecttime = models.IntegerField(null=True)
#     SLv2Cooldown = models.CharField(max_length=20)
#     SLv3Pierce = models.CharField(max_length=10, null=True)
#     SLv3Power = models.CharField(max_length=10, null=True)
#     SLv3Magazine = models.IntegerField(null=True)
#     SLv3Effect = models.CharField(max_length=10, null=True)
#     SLv3Effecttime = models.IntegerField(null=True)
#     SLv3Cooldown = models.CharField(max_length=20)
#     SLv4Pierce = models.CharField(max_length=10, null=True)
#     SLv4Power = models.CharField(max_length=10, null=True)
#     SLv4Magazine = models.IntegerField(null=True)
#     SLv4Effect = models.CharField(max_length=10, null=True)
#     SLv4Effecttime = models.IntegerField(null=True)
#     SLv4Cooldown = models.CharField(max_length=20)
#     SLv5Pierce = models.CharField(max_length=10, null=True)
#     SLv5Power = models.CharField(max_length=10, null=True)
#     SLv5Magazine = models.IntegerField(null=True)
#     SLv5Effect = models.CharField(max_length=10, null=True)
#     SLv5Effecttime = models.IntegerField(null=True)
#     SLv5Cooldown = models.CharField(max_length=20)
#     SLv6Pierce = models.CharField(max_length=10, null=True)
#     SLv6Power = models.CharField(max_length=10, null=True)
#     SLv6Magazine = models.IntegerField(null=True)
#     SLv6Effect = models.CharField(max_length=10, null=True)
#     SLv6Effecttime = models.IntegerField(null=True)
#     SLv6Cooldown = models.CharField(max_length=20)
#     SLv7Pierce = models.CharField(max_length=10, null=True)
#     SLv7Power = models.CharField(max_length=10, null=True)
#     SLv7Magazine = models.IntegerField(null=True)
#     SLv7Effect = models.CharField(max_length=10, null=True)
#     SLv7Effecttime = models.IntegerField(null=True)
#     SLv7Cooldown = models.CharField(max_length=20)
#     SLv8Pierce = models.CharField(max_length=10, null=True)
#     SLv8Power = models.CharField(max_length=10, null=True)
#     SLv8Magazine = models.IntegerField(null=True)
#     SLv8Effect = models.CharField(max_length=10, null=True)
#     SLv8Effecttime = models.IntegerField(null=True)
#     SLv8Cooldown = models.CharField(max_length=20)
#     SLv9Pierce = models.CharField(max_length=10, null=True)
#     SLv9Power = models.CharField(max_length=10, null=True)
#     SLv9Magazine = models.IntegerField(null=True)
#     SLv9Effect = models.CharField(max_length=10, null=True)
#     SLv9Effecttime = models.IntegerField(null=True)
#     SLv9Cooldown = models.CharField(max_length=20)
#     SLv10Pierce = models.CharField(max_length=10, null=True)
#     SLv10Power = models.CharField(max_length=10, null=True)
#     SLv10Magazine = models.IntegerField(null=True)
#     SLv10Effect = models.CharField(max_length=10, null=True)
#     SLv10Effecttime = models.IntegerField(null=True)
#     SLv10Cooldown = models.CharField(max_length=20)

# class Trait(models.Model):
#     Status = models.ForeignKey('Status', null = True,on_delete = models.SET_NULL)
#     Traits1Name = models.CharField(max_length=100)
#     T1Lv1Effect = models.CharField(max_length=10)
#     T1Lv2Effect = models.CharField(max_length=10)
#     T1Lv3Effect = models.CharField(max_length=10)
#     T1Lv4Effect = models.CharField(max_length=10)
#     T1Lv5Effect = models.CharField(max_length=10)
#     T1Lv6Effect = models.CharField(max_length=10)
#     T1Lv7Effect = models.CharField(max_length=10)
#     T1Lv8Effect = models.CharField(max_length=10)
#     T1Lv9Effect = models.CharField(max_length=10)
#     T1Lv10Effect = models.CharField(max_length=10)
#     Traits2Name = models.CharField(max_length=100, null=True)
#     T2Lv1Effect = models.CharField(max_length=10, null=True)
#     T2Lv2Effect = models.CharField(max_length=10, null=True)
#     T2Lv3Effect = models.CharField(max_length=10, null=True)
#     T2Lv4Effect = models.CharField(max_length=10, null=True)
#     T2Lv5Effect = models.CharField(max_length=10, null=True)
#     T2Lv6Effect = models.CharField(max_length=10, null=True)
#     T2Lv7Effect = models.CharField(max_length=10, null=True)
#     T2Lv8Effect = models.CharField(max_length=10, null=True)
#     T2Lv9Effect = models.CharField(max_length=10, null=True)
#     T2Lv10Effect = models.CharField(max_length=10, null=True)


# Create your models here.
