# Generated by Django 3.1 on 2021-03-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ivents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IventName', models.CharField(max_length=100)),
                ('Disabled', models.DateTimeField()),
                ('URL', models.CharField(max_length=2048)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskList.categorymaster')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categorymaster',
            constraint=models.UniqueConstraint(fields=('Category',), name='CategoryMasterFilter_unique'),
        ),
        migrations.AddConstraint(
            model_name='ivents',
            constraint=models.UniqueConstraint(fields=('IventName',), name='IventsFilter_unique'),
        ),
    ]
