# Generated by Django 3.2.5 on 2021-10-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0002_auto_20211001_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSName', models.CharField(max_length=100)),
                ('Attribute', models.CharField(max_length=10)),
                ('MSNumber', models.CharField(max_length=100)),
                ('WorkName', models.CharField(max_length=100)),
                ('Rarity', models.IntegerField()),
            ],
        ),
    ]
