# Generated by Django 3.2.5 on 2021-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0004_auto_20211006_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='MSNumber',
            field=models.CharField(max_length=50),
        ),
    ]
