# Generated by Django 3.2.5 on 2021-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0005_alter_unit_msnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ShowcaseTweet',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
