# Generated by Django 3.2.5 on 2022-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0006_unit_showcasetweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='SLv10Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv10Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv10Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv10Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv10Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv2Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv2Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv2Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv2Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv2Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv3Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv3Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv3Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv3Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv3Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv4Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv4Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv4Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv4Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv4Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv5Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv5Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv5Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv5Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv5Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv6Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv6Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv6Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv6Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv6Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv7Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv7Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv7Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv7Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv7Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv8Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv8Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv8Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv8Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv8Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv9Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv9Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv9Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv9Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SLv9Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Slv1Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Slv1Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Slv1Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Slv1Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Slv1Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv10Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv1Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv2Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv3Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv4Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv5Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv6Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv7Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv8Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='T2lv9Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='Traits2Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
