# Generated by Django 3.2.5 on 2022-01-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0007_auto_20220104_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Slv1Cooldown',
            new_name='SLv1Cooldown',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Slv1Effect',
            new_name='SLv1Effect',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Slv1Effecttime',
            new_name='SLv1Effecttime',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Slv1Magazine',
            new_name='SLv1Magazine',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Slv1Power',
            new_name='SLv1Power',
        ),
    ]
