# Generated by Django 3.2.5 on 2022-01-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0008_auto_20220110_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv10Effect',
            new_name='T1Lv10Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv1Effect',
            new_name='T1Lv1Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv2Effect',
            new_name='T1Lv2Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv3Effect',
            new_name='T1Lv3Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv4Effect',
            new_name='T1Lv4Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv5Effect',
            new_name='T1Lv5Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv6Effect',
            new_name='T1Lv6Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv7Effect',
            new_name='T1Lv7Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv8Effect',
            new_name='T1Lv8Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T1lv9Effect',
            new_name='T1Lv9Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv10Effect',
            new_name='T2Lv10Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv1Effect',
            new_name='T2Lv1Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv2Effect',
            new_name='T2Lv2Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv3Effect',
            new_name='T2Lv3Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv4Effect',
            new_name='T2Lv4Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv5Effect',
            new_name='T2Lv5Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv6Effect',
            new_name='T2Lv6Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv7Effect',
            new_name='T2Lv7Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv8Effect',
            new_name='T2Lv8Effect',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='T2lv9Effect',
            new_name='T2Lv9Effect',
        ),
    ]
