# Generated by Django 3.2.5 on 2022-01-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0009_auto_20220110_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Slv1Pierce',
            new_name='SLv1Pierce',
        ),
    ]
