# Generated by Django 3.2.5 on 2022-04-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0013_alter_status_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentUnitOf', to='Chartview.unit'),
        ),
    ]
