# Generated by Django 3.2.5 on 2022-04-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0015_alter_status_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='MSName',
        ),
        migrations.RemoveField(
            model_name='status',
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='status',
            name='MSName',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='MSName',
        ),
    ]
