# Generated by Django 3.2.5 on 2022-04-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0017_auto_20220411_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Attribute',
            field=models.CharField(default='aaa', max_length=20),
            preserve_default=False,
        ),
    ]
