# Generated by Django 3.2.5 on 2022-04-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0018_status_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='Status',
        ),
        migrations.AddField(
            model_name='status',
            name='SLv10Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv10Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv10Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv10Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv10Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv10Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv1Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv1Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv1Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv1Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv1Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv1Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv2Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv2Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv2Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv2Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv2Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv2Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv3Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv3Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv3Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv3Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv3Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv3Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv4Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv4Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv4Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv4Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv4Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv4Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv5Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv5Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv5Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv5Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv5Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv5Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv6Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv6Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv6Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv6Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv6Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv6Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv7Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv7Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv7Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv7Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv7Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv7Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv8Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv8Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv8Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv8Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv8Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv8Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv9Cooldown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv9Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv9Effecttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv9Magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv9Pierce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SLv9Power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SkillCategory',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SkillName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='SkillText',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv10Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv1Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv2Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv3Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv4Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv5Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv6Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv7Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv8Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T1Lv9Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv10Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv1Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv2Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv3Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv4Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv5Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv6Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv7Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv8Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='T2Lv9Effect',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='Traits1Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='Traits2Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Trait',
        ),
    ]
