# Generated by Django 3.2.5 on 2022-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chartview', '0019_auto_20220423_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='MaxRarity',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
